sudo: required

language: java

services:
  - docker
  
env:
  - TMPDIR=/tmp
  
before_install:
  - docker pull ubuntu:xenial
  
after_success:
  - mvn deploy --settings travis-config.xml -DskipTests=true -B
