sudo: required

language: java

services:
  - docker
  
env:
  - TMPDIR=/tmp
  
before_install:
  - docker pull ubuntu:xenial

after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      mvn deploy --settings travis-config.xml -DskipTests=true -B
    fi